# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QWidget

import sys

from suggest import *
from predict import *
import speech_recognition as sr

class Ui_MainWindow(object):
    def push1(self):
        self.window=QtWidgets.QWidget()
        self.ui=Ui_Suggestion()
        self.ui.setupUi1(self.window)
        self.window.show()
        MainWindow.hide()

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 557)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")

        self.Back = QtWidgets.QLabel(self.widget)
        self.Back.setGeometry(QtCore.QRect(0, 0, 791, 561))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.Back.setFont(font)
        self.Back.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Back.setAutoFillBackground(False)
        self.Back.setStyleSheet("QLabel#Back{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(14, 8, 73, 255), stop:0.636364 rgba(28, 17, 145, 255), stop:0.818182 rgba(14, 11, 234, 255), stop:0.880682 rgba(5, 92, 244, 255), stop:0.926136 rgba(36, 0, 255, 255), stop:1 rgba(55, 83, 239, 255))}\n"
"")
        self.Back.setFrameShape(QtWidgets.QFrame.Box)
        self.Back.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Back.setLineWidth(4)
        self.Back.setText("")
        self.Back.setAlignment(QtCore.Qt.AlignCenter)
        self.Back.setWordWrap(True)
        self.Back.setIndent(0)
        self.Back.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Back.setObjectName("Back")

        self.TIT = QtWidgets.QLabel(self.widget)
        self.TIT.setGeometry(QtCore.QRect(210, 10, 411, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.TIT.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.TIT.setFont(font)
        self.TIT.setAutoFillBackground(False)
        self.TIT.setStyleSheet("QLabel#TIT{\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"}")
        self.TIT.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.TIT.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TIT.setScaledContents(True)
        self.TIT.setAlignment(QtCore.Qt.AlignCenter)
        self.TIT.setObjectName("TIT")

        self.TXT = QtWidgets.QLabel(self.widget)
        self.TXT.setGeometry(QtCore.QRect(40, 140, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TXT.setFont(font)
        self.TXT.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);}")
        self.TXT.setObjectName("TXT")

        self.TXTIP = QtWidgets.QLineEdit(self.widget)
        self.TXTIP.setGeometry(QtCore.QRect(270, 159, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.TXTIP.setFont(font)
        self.TXTIP.setObjectName("TXTIP")

        self.OR = QtWidgets.QLabel(self.widget)
        self.OR.setGeometry(QtCore.QRect(390, 210, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OR.setFont(font)
        self.OR.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.OR.setAlignment(QtCore.Qt.AlignCenter)
        self.OR.setObjectName("OR")

        self.Suggest = QtWidgets.QPushButton(self.widget)
        self.Suggest.setEnabled(True)
        self.Suggest.setGeometry(QtCore.QRect(310, 470, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Suggest.setFont(font)
        self.Suggest.setAutoFillBackground(False)
        self.Suggest.setStyleSheet("QPushButton{\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    border-color: rgb(255, 255, 255);\n"
"    border-top-color: rgb(255, 255, 255);\n"
"    border-right-color: rgb(255, 255, 255);\n"
"    border-left-color: rgb(255, 255, 255)\n"
"}")
        self.Suggest.setText("Suggest Words")
        self.Suggest.setFlat(True)
        self.Suggest.setObjectName("Suggest")

        self.Suggest.clicked.connect(self.data1)
        #self.Suggest.clicked.connect(self.push1)


        self.Mic = QtWidgets.QPushButton(self.widget)
        self.Mic.setGeometry(QtCore.QRect(300, 260, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Mic.setFont(font)
        self.Mic.setStyleSheet("QPushButton{color:rgb(255, 255, 255)}")
        self.Mic.setFlat(True)
        self.Mic.setObjectName("Mic")

        self.Mic.clicked.connect(self.data)

        self.Mic_op = QtWidgets.QTextEdit(self.widget)
        self.Mic_op.setGeometry(QtCore.QRect(160, 330, 511, 111))
        self.Mic_op.setObjectName("Mic_op")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Mic_op.setFont(font)
    

        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    global text
    text = 'jash'

    def data(self):
        global text
        r = sr.Recognizer()
        try:
            with sr.Microphone() as source2:
                r.adjust_for_ambient_noise(source2,duration=0.2)
                audio2 = r.listen(source2)               
                text = r.recognize_google(audio2)
                self.Mic_op.setText(text)       
        except sr.RequestError as e:
            print("Could not request results;{0}".format(e))
    
        except sr.UnknownValueError:
            print("Unknown Error Occured")
        return text

    def data1(self): 
        a = self.TXTIP.text()  
        if text == 'jash':
            q = self.TXTIP.text()  
            seq = " ".join(tokenizer.tokenize(q.lower())[0:5])
            a1=predict_completions(seq, 5)
            for i in a1:
                list1.append(q+" "+i+";")
            str1=" "
            box1=str1.join(list1)
            self.box1=box1
            self.window=QtWidgets.QWidget()
            self.ui=Ui_Suggestion(self.box1)
            self.ui.setupUi1(self.window)
            self.window.show()
            MainWindow.hide()

        elif len(a) == 0:
            q=text
            seq = " ".join(tokenizer.tokenize(q.lower())[0:5])
            a1=predict_completions(seq, 5)
            for i in a1:
                list1.append(q+" "+i+";")
            str1=" "
            box1=str1.join(list1)
            self.box1=box1
            self.window=QtWidgets.QWidget()
            self.ui=Ui_Suggestion(self.box1)
            self.ui.setupUi1(self.window)
            self.window.show()
            MainWindow.hide()
        else:
            print("404 Not Found")
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TIT.setText(_translate("MainWindow", "Next Word Predictor"))
        self.TXT.setText(_translate("MainWindow", "Enter the Sentence:"))
        self.OR.setText(_translate("MainWindow", "OR"))
        self.Mic.setText(_translate("MainWindow", "Microphone"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)    
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
