# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Suggest.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QWidget,QDialog

import sys

from main import*
from predict import*

class Ui_Suggestion(object):
    def setupUi1(self, Suggestion):
        Suggestion.setObjectName("Suggestion")
        Suggestion.resize(421, 333)
        Suggestion.setStyleSheet("")
        self.label = QtWidgets.QLabel(Suggestion)
        self.label.setGeometry(QtCore.QRect(0, 0, 421, 331))
        self.label.setStyleSheet("QLabel{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(14, 8, 73, 255), stop:0.636364 rgba(28, 17, 145, 255), stop:0.818182 rgba(14, 11, 234, 255), stop:0.880682 rgba(5, 92, 244, 255), stop:0.926136 rgba(36, 0, 255, 255), stop:1 rgba(55, 83, 239, 255));\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")

        self.box = QtWidgets.QTextEdit(Suggestion)
        self.box.setGeometry(QtCore.QRect(10, 10, 401, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.box.setFont(font)
        self.box.setObjectName("box")
        

        #self.box.setText(box1)

        self.Hear = QtWidgets.QPushButton(Suggestion)
        self.Hear.setGeometry(QtCore.QRect(34, 270, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.Hear.setFont(font)
        self.Hear.setObjectName("Hear")

        self.Hear.clicked.connect(self.hear)

        self.Close = QtWidgets.QPushButton(Suggestion)
        self.Close.setGeometry(QtCore.QRect(310, 270, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.Close.setFont(font)
        self.Close.setObjectName("Close")
        self.Close.clicked.connect(lambda:sys.exit())


        self.retranslateUi(Suggestion)
        QtCore.QMetaObject.connectSlotsByName(Suggestion)

    def hear(self):
        import pyttsx3
        import os 
        engine = pyttsx3.init('sapi5')
        engine.say(self.box1)
        engine.runAndWait()
        engine.stop()

    def __init__(self,box1):
        self.box1=box1
        print(box1)
    def retranslateUi(self, Suggestion):
        _translate = QtCore.QCoreApplication.translate
        Suggestion.setWindowTitle(_translate("Suggestion", "Dialog"))
        self.box.setText(_translate("Suggestion",self.box1))
        self.Hear.setText(_translate("Suggestion", "Hear Out Words "))
        self.Close.setText(_translate("Suggestion", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Suggestion = QDialog()
    ui = Ui_Suggestion()
    ui.setupUi1(Suggestion)
    Suggestion.show()
    sys.exit(app.exec_())
